NDK version script is changed

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -224,8 +224,13 @@ workflows:
         title: Deactivate License
         inputs:
         - content: |-
-            #!/bin/bash
+             #!/usr/bin/env bash
             # fail if any commands fails
+            set -e
+            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+            set -o pipefail
+            # debug log
+            set -x
 
             /Applications/Unity/Unity.app/Contents/MacOS/Unity -quit -batchmode -logFile -returnlicense
     meta:
